services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: paygo
      MYSQL_USER: paygo_user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: